name: VRChat Package Lister
description:
  Extract package data from multiple VRChat repositories and generate a package
  list.
author: Limitex

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: upload-cloud
  color: blue

# Define your inputs here.
inputs:

# Define your outputs here.
outputs:

runs:
  using: node20
  main: dist/index.js
