name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Check Format
        id: npm-format-check
        run: npm run format:check

      - name: Lint
        id: npm-lint
        run: npm run lint

      - name: Test
        id: npm-ci-test
        run: npm run ci-test

  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          package-title: 'Test Action'
          package-author: 'Test Author'
          package-id: 'test-action'
          package-url: 'https://github.com/test-action'
          repositories: 'actions/typescript-action'
          output: './dist'
          filename: 'index.json'
          minified: true

      - name: Print Output
        id: output
        run: |
          echo "Package: ${{ steps.test-action.outputs.package }}"
          echo "Filename: ${{ steps.test-action.outputs.filename }}"
          echo "Output: ${{ steps.test-action.outputs.output }}"
          echo "Path: ${{ steps.test-action.outputs.path }}"
